// Generated by https://quicktype.io
export interface DatesParients {
    Apellidos:       string;
    Correo:          string;
    FechaNacimiento: string;
    FotoPerfil:      string;
    IdPaciente:      string;
    Nombre:          string;
    Password:        string;
    Tipo:            string;
}

