// Generated by https://quicktype.io
export interface Login {
    code:    number;
    data:    Data;
    error:   null;
    message: string;
    status:  string;
}

export interface Data {
    Apellidos:       string;
    Correo:          string;
    FechaNacimiento: string;
    FotoPerfil?:      string;
    IdUser:          string;
    Nombre:          string;
}

export interface Roles {
    code:    number;
    error:   null;
    message: string;
    roles:   RolesClass;
    status:  string;
}

export interface RolesClass {
    IdUser:      string;
    RolDoctor:   boolean;
    RolFamiliar: boolean;
    RolPaciente: boolean;
    data:        Data;
}

export interface ChatBotMessages{
    name: string;
    message: string;
}

export interface TotalPaciente {
    total: number;
}
