// Generated by https://quicktype.io

export interface Login {
    code:    number;
    data:    Data;
    error:   null;
    message: string;
    status:  string;
}

export interface Data {
    Apellidos:       string;
    Correo:          string;
    FechaNacimiento: string;
    FotoPerfil:      string;
    IdUser:          string;
    Nombre:          string;
}
