// Generated by https://quicktype.io

export interface ListaPacientes {
    code:    number;
    data:    Data;
    error:   null;
    message: string;
    status:  string;
}

export interface Data {
    total:    number;
    usuarios: Usuario[];
}

export interface Usuario {
    Apellidos:       string;
    Correo:          string;
    FechaNacimiento: string;
    FotoPerfil?:     string;
    Password?:       string;
    IdUser:          string;
    Nombre:          string;
}